{{- $user := (randAlpha 8) }}
{{- $password := (randAlpha 20) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-boot-api.fullname" . }}
  labels:
    {{- include "spring-boot-api.labels" . | nindent 4 }}
data:
  .credentials.json: |
    {{ printf "{ \"user\": \"%s\", \"password\": \"%s\" }" $user $password | b64enc}}
